@startuml
'https://plantuml.com/sequence-diagram

skinparam object{
    BackgroundColor Cyan
}

skinparam class{
    BackgroundColor LightGreen
}

class mini_cooper <<(C,Plum)>> {
    model_name TEXT
    generation INT
    model_type TEXT
    color TEXT
    price INT
    km_driven INT
    max_range INT
    weight INT
    fuel_type TEXT
    geartype TEXT
    yearly_tax INT
    base64_images TEXT[]
}

class account <<(C,Plum)>>{
    name TEXT
    password TEXT
    phone INT
    email TEXT
    city TEXT
    address TEXT
}

class ev_mini_cooper <<(C,Plum)>>{
    base_cooper mini_cooper
    charge_capacity INT
    km_pr_kwh FLOAT
}

class fossil_mini_cooper <<(C,Plum)>>{
    base_cooper mini_cooper
    tank_capacity INT
    km_pr_liter FLOAT
    gears INT
}

class hybrid_mini_cooper <<(C,Plum)>>{
    base_cooper mini_cooper
    fuel_type1 TEXT
    fuel_type2 TEXT
    tank_capacity INT
    charge_capacity INT
    km_pr_liter FLOAT
    km_pr_kwh FLOAT
    gears INT
}

class Car <<(C,Plum)>>{
    fossil_mini_cooper?
    ev_mini_cooper?
    hybrid_mini_cooper?
}

object users {
    id SERIAL PRIMARY KEY
    a_user account
}


object Cars {
    id SERIAL PRIMARY KEY
    car Car
    account_id INT
    CONSTRAINT FK_account_id FOREIGN KEY (account_id) REFERENCES users (id)
}

Car --|> fossil_mini_cooper
Car --|> ev_mini_cooper
Car --|> hybrid_mini_cooper

users::id -> Cars::id

Car --> Cars

fossil_mini_cooper --|> mini_cooper
ev_mini_cooper --|> mini_cooper
hybrid_mini_cooper --|> mini_cooper

account -> users::a_user

@enduml

@startuml
skinparameters
@enduml